<h1><?= $tila['tila'] ?></h1>


<form action="muuta" method="post">
<input type="hidden" name="tila" value="<?= $tila['tila'] ?>">
<table>
  <tr>
    <td>Ensimmäinen varaus</td><td>Viimeinen varaus</td><td>Hinta</td><td>Muuta</td>
  </tr>
   <tr>
     <td><input type="text" name="alkuaika" value="<?= $tila['alkuaika'] ?>">:00</td> 
      <td><input type="text" name="loppuaika" value="<?= $tila['loppuaika'] -1 ?>">:00</td> 
      <td><input type="text" name="hinta" value ="<?= $tila['hinta'] ?>"> &#8364/h</td>
      <td><input type="text" name="muuta" value="<?= $tila['muuta'] ?> "></td>
   </tr>
</table>
<input type="submit" value="Tallenna muutokset">
</form>
<p>

<h3>Varaukset</h3>
<table>
<?php
echo mktime(0, 0, 0, date("m"), date("d"), date("Y"));
for($i = $tila['alkuaika']; $i < $tila['loppuaika']; $i++){
   echo "<tr><td>$i:00</td>";
   if($varaus['alkuaika'] == $i)
      echo "<td>Varattu</td>";
   echo "</tr>";
}
?>
<table>
