<h1>Isännöitsijän toiminnot</h1>

<a href="<?php echo Atomik::url('index'); ?>">Etusivulle</a>
<a href="<?php echo Atomik::url('logout'); ?>">Kirjaudu ulos</a><br>
<p>
    <a href="<?php echo Atomik::url('admin/laskut'); ?>">Laskujen hallinta</a><br>
    <a href="<?php echo Atomik::url('admin/kayttajat'); ?>">Halinnoi käyttäjiä</a><br>
    <a href="<?php echo Atomik::url('admin/tilat'); ?>">Muokkaa tiloja</a><br>
    <a href="<?php echo Atomik::url('admin/kaikkiVaraukset'); ?>">Kaikki varaukset</a><br>
</p>

<h2>Tulevat varaukset</h2>

<table class="varaus">
    <tr>
        <td class="varaus"><b>Aika</b></td>
        <td class="varaus"><b>Tila</b></td>
        <td class="varaus"><b>Varaaja</b></td>
        <td class="varaus"></td>
    </tr>
<?php foreach($varaukset as $varaus) { ?>
    <tr>
        <td class="varaus"><b><?php echo $this->muotoile_paiva($varaus['pvm']); ?></b>
              <?php echo $this->muotoile_aika($varaus['alkuaika'], $varaus['loppuaika']); ?></td>
        <td class="varaus"><?php echo $varaus['tila']; ?></td>
        <td class="varaus"><?php echo $varaus['varaaja']; ?></td>
        <td class="varaus">Peruuta varaus</td>
    </tr>
<?php } ?>

</table>