<h1>Taloyhtion tilojen varaus</h1>

<b><?php echo Atomik::get('session/user'); ?></b> kirjautuneena sisään. 
<a href='<?php echo Atomik::url('vaihdaSalasana'); ?>'>Vaihda salasana</a> 
<a href='<?php echo Atomik::url('logout'); ?>'>Kirjaudu ulos</a><br>

Tänään on <?php echo date("d.m.Y"); ?>

<ul>
<?php foreach ($tilat as $tila) { ?>
	<li><a href='<?php echo Atomik::url('tila', array('tila' => $tila[0])); ?>'>
                <?php echo $tila[0]; ?></a></li> <?}?>
</ul>

<br>
<?php if(!$this->testAdmin()){ ?>
Sinulla on <?php echo $maksamattomat; ?> kpl laskuttamattomia varauksia.<br>
<a href="<? echo Atomik::url('teeLasku', array('user' => Atomik::get('session/user'))); ?>"
   target="new">Tee lasku varauksistasi</a><br>
<?php } else { ?>
   <a href="<?php echo Atomik::url('admin'); ?>">Isännöitsijän toiminnot</a><br>
<?php } ?>
<h3>Omat varaukset</h3>
<table class="varaus">
    <tr>
        <td class="varaus"><b>Päivä</b></td>
        <td class="varaus"><b>Tila</b></td>
        <td class="varaus"><b>Aika</b></td>
        <td class="varaus"><b>Ovikoodi</b></td>
        <td ></td>
    </tr>
<?php if($varauksia != 0) {
    foreach($varaus as $rivi) { ?>
    <tr>
        <td class="varaus"><b><?php echo $this->muotoile_paiva($rivi['pvm']); ?></b></td>
        <td class="varaus"> <?php echo $rivi['tila']; ?></td> 
        <td class="varaus"><?php echo $this->muotoile_aika($rivi['alkuaika'], $rivi['loppuaika']); ?> </td>
        <td class="varaus"><?php echo $rivi['ovikoodi']; ?></td>
        <td class="varaus">
            <?php echo $this->peruutus($rivi['tunniste']); ?>
                
        </td>
    </tr>
<?php  }
}?>
</table>