<h1>Taloyhtion palvelut</h1>

<?php echo Atomik::get('session/user'); ?> kirjautuneena sisään. 
<a href='<?php echo Atomik::url('logout'); ?>'>Kirjaudu ulos</a>

<?php echo date("d-m-Y"); ?>

<ul>
<?php foreach ($tilat as $tila) { ?>
	<li><a href='<?php echo Atomik::url('tila', array('tila' => $tila[0])); ?>'>
                <?php echo $tila[0]; ?></a></li> <?}?>
</ul>

<br>
<a href="<? echo Atomik::url('teeLasku', array('user' => Atomik::get('session/user'))); ?>"
   target="new">Tee lasku maksamattomista varauksistasi</a><br>

<h3>Omat varaukset</h3>
<ul>
<?php if($varauksia == true) {
    foreach($varaus as $rivi) { ?>
    <li><?php echo $rivi['pvm']; ?> <?php echo $rivi['tila'] ?> 
    <?php echo $this->muotoile_aika($rivi['alkuaika'], $rivi['loppuaika']) ?></li>
<?php  }
}?>
</ul>