<h1>Taloyhtion tilojen varaus</h1>

<?php echo Atomik::get('session/user'); ?> kirjautuneena sisään. 
<a href='<?php echo Atomik::url('logout'); ?>'>Kirjaudu ulos</a><br>

Tänään on <?php echo date("d.m.Y"); ?>

<ul>
<?php foreach ($tilat as $tila) { ?>
	<li><a href='<?php echo Atomik::url('tila', array('tila' => $tila[0])); ?>'>
                <?php echo $tila[0]; ?></a></li> <?}?>
</ul>

<br>
<?php if(!$this->testAdmin()){ ?>
Sinulla on <?php echo $maksamattomat; ?> kpl laskuttamattomia varauksia.<br>
<a href="<? echo Atomik::url('teeLasku', array('user' => Atomik::get('session/user'))); ?>"
   target="new">Tee lasku varauksistasi</a><br>
<?php } else { ?>
   <a href="<?php echo Atomik::url('laskut'); ?>">Laskujen hallinta</a><br>
<?php } ?>
<h3>Omat varaukset</h3>
<ul>
<?php if($varauksia != 0) {
    foreach($varaus as $rivi) { ?>
    <li><b><?php echo $this->muotoile_paiva($rivi['pvm']); ?></b> <?php echo $rivi['tila'] ?> 
    <?php echo $this->muotoile_aika($rivi['alkuaika'], $rivi['loppuaika']) ?> 
        <?php echo $rivi['ovikoodi']; ?>
        <a href="<? echo Atomik::url('peruuta', array('tunniste' => $rivi['tunniste'])); ?>">
        Peruuta varaus</a></li>
<?php  }
}?>
</ul>