<h1>Laskut</h1>

<br>

    <h3>Laskuta käyttäjiä</h3>
        <?php foreach($users as $nimi){ ?>
        <a href="<?php echo Atomik::url('teeLasku', array('user' => $nimi)); ?>" target="new">
                <?php echo $nimi; ?></a></li><br>
        <?php } ?>


<h2>Laskut</h2>
<table>
<?php foreach($laskut as $lasku){ ?>
    <tr>
        <td><?= $lasku['viite'] ?></td>
        <td><?= $lasku['maksaja'] ?></td>
        <td><?= $this->muotoile_paiva($lasku['erapaiva']) ?></td>
        <td><?= $lasku['summa'] ?></td>
        <td><?= $this->maksun_tila($lasku['maksettu'])  ?></td>
    </tr>
<? }?>
</table>
