<h1>Laskut</h1>

<a href="<?php echo Atomik::url('index'); ?>">Takaisin</a>
<br>

    <h3>Laskuta käyttäjiä</h3>
        <?php foreach($users as $nimi){ ?>
        <a href="<?php echo Atomik::url('teeLasku', array('user' => $nimi)); ?>" target="new">
                <?php echo $nimi; ?></a></li><br>
        <?php } ?>


<h2>Laskut</h2>
<table>
<?php foreach($laskut as $lasku){ ?>
    <tr>
        <td><?php echo $lasku['viite']; ?></td>
        <td><?php echo $lasku['maksaja']; ?></td>
        <td><?php echo $this->muotoile_paiva($lasku['erapaiva']); ?></td>
        <td><?php echo $lasku['summa']; ?></td>
        <td><?php echo $this->maksun_tila($lasku['maksettu']); ?></td>
        <td><?php if(!$lasku['maksettu']) { ?>
            <a href="<? echo Atomik::url('merkitseMaksetuksi', array('viite' => $lasku['viite'])); ?>">
                Merkitse maksetuksi</a> <?php } ?></td>
    </tr>
<?php }?>
</table>
