<h1>Taloyhtiön varauskalenteri</h1>

<h2>Kirjaudu sisään</h2>
<?php if (Atomik::get('session/user') == ''){ //Kirjautumisen tarkastus ?>
        <form action='' method='post'>
            <table>
                <tr><td>Asunto:</td> <td><input type='text' name='user'></td></tr>
                <tr><td>Salasana:</td><td> <input type='password' name='pass'></td></tr>
            </table>
            <br>
            <input type='submit' value='Kirjaudu sisään'>
    <?php return;}?>
