<center>
<h1>Taloyhtiön varauskalenteri</h1>

<?php if (Atomik::get('session/user') == ''){ //Kirjautumisen tarkastus ?>
        <form action='' method='post' id="login">
            <h2>Kirjaudu sisään</h2>
            <table>
                <tr><td>Asunto:</td> <td><input type='text' name='user'></td></tr>
                <tr><td>Salasana:</td><td> <input type='password' name='pass'></td></tr>
                <tr><td></td><td><input type='submit' value='Kirjaudu sisään'></td></tr>
            </table>
            
    <?php return;}?>
</center>