<h1>Lasku taloyhtiön palveluiden käytöstä</h1>

Palveleva taloyhtiö as. oy<br>
Varaustie 2<br>
1234 Helsinki<br>
<p>
    <table>
    <? foreach($varaus as $rivi) { ?>
        <tr>
            <td>Varausnumero</td><td>Päivämäärä</td><td>Varattu tila</td><td>Aika</td><td>Hinta</td>
        </tr>
        <tr>
            <td><?= $rivi['tunniste'] ?></td>
            <td><?= $rivi['pvm'] ?></td><td><?= $rivi['tila'] ?></td>
            <td><?= $this->muotoile_aika($rivi['alkuaika'], $rivi['loppuaika']) ?></td>
            <td><?= $rivi['hinta'] ?></td>
        </tr>
    <? } ?>
    </table>
</p>

<strong>Yhteensä:</strong> <?= $yhteensa ?> €<br>
Viitenumero: <?= $viite ?><br>
<br>
Maksetaan tilille 12345-1654626<br>
Eräpäivä: <?= $this->muotoile_paiva($erapaiva) ?>
