<h1><?php echo $tila['tila']; ?></h1>


<table>
  <tr>
    <td>Ensimmäinen varaus</td><td>Viimeinen varaus</td><td>Hinta</td><td>Muuta</td>
  </tr>
   <tr>
     <td><?php echo $tila['alkuaika']; ?>:00</td> 
      <td><?php echo ($tila['loppuaika'] -1); ?>:00</td> 
      <td><?php echo $tila['hinta']; ?> &#8364/h</td>
      <td><?php echo $tila['muuta']; ?></td>
   </tr>
</table>
<br>
<a href="<?php echo Atomik::url('index'); ?>">Takaisin</a>
<p>

<h3>Varaukset</h3>
<table id="varaustaulukko"><tr><td class="varaus"></td>
<?php //Kalenterin tulostus
for($i = 0; $i <= 13; $i++){  ?>
   <td class='varaus'> <?php echo $this->muotoile_paiva($date[$i]); ?></td> <?php } ?>
    </tr>

<?php for($i = $tila['alkuaika']; $i < $tila['loppuaika']; $i++){ ?>
   <tr><td class="varaus"><?php echo "$i:00"; ?></td>
<?php for($k = 0; $k < 14; $k++){
       $vt = 0;
       foreach ($varaus as $v){
           if($v['alkuaika'] <= $i && $i < $v['loppuaika'] && $v['pvm'] == $date[$k]){ ?>
             <td class="varattu">Varattu</td>
          <?php $vt = 1;
           }
       }
           if($vt == 0){ ?>
              <td class="vapaa">
              <a class="varaa" href="<?php echo Atomik::url('varaa', array('tila' => $tila['tila'],
                  'aika' => $i, 'pvm' => $date[$k])); ?>">Varaa</a>
              </td>
              
           <?php }
   } ?>
    </tr>
<?php }
?>
<table>