<h1><?= $tila['tila'] ?></h1>


<form action="muuta" method="post">
<input type="hidden" name="tila" value="<?= $tila['tila'] ?>">
<table>
  <tr>
    <td>Ensimmäinen varaus</td><td>Viimeinen varaus</td><td>Hinta</td><td>Muuta</td>
  </tr>
   <tr>
     <td><input type="text" name="alkuaika" value="<?= $tila['alkuaika'] ?>">:00</td> 
      <td><input type="text" name="loppuaika" value="<?= $tila['loppuaika'] -1 ?>">:00</td> 
      <td><input type="text" name="hinta" value ="<?= $tila['hinta'] ?>"> &#8364/h</td>
      <td><input type="text" name="muuta" value="<?= $tila['muuta'] ?>"></td>
   </tr>
</table>
<input type="submit" value="Tallenna muutokset">
</form>
<br>
<a href="<? echo Atomik::url('index'); ?>">Takaisin</a>
<p>

<h3>Varaukset</h3>
<table><tr><td></td>
<? //Kalenterin tulostus
for($i = 0; $i < 14; $i++)
   echo "<td>$date[$i]</td>"; ?>
    </tr>

<? for($i = $tila['alkuaika']; $i < $tila['loppuaika']; $i++){ ?>
   <tr><td><? echo "$i:00"; ?></td>
<? for($k = 0; $k < 14; $k++){
       $vt = 0;
       foreach ($varaus as $v){
           if($v['alkuaika'] <= $i && $i < $v['loppuaika'] && $v['pvm'] == $date[$k]){ ?>
             <td class="varattu">Varattu</td>
          <? $vt = 1;
           }
       }
           if($vt == 0){ ?>
              <td class="vapaa">
              <a class="varaa" href="<? echo Atomik::url('varaa', array('tila' => $tila['tila'],
                  'aika' => $i, 'pvm' => $date[$k])); ?>">Varaa</a>
              </td>
              
           <? }
   } ?>
    </tr>
<?}
?>
<table>