<h1><?= $tila['tila'] ?></h1>


<form action="muuta" method="post">
<input type="hidden" name="tila" value="<?= $tila['tila'] ?>">
<table>
  <tr>
    <td>Ensimmäinen varaus</td><td>Viimeinen varaus</td><td>Hinta</td><td>Muuta</td>
  </tr>
   <tr>
     <td><input type="text" name="alkuaika" value="<?= $tila['alkuaika'] ?>">:00</td> 
      <td><input type="text" name="loppuaika" value="<?= $tila['loppuaika'] -1 ?>">:00</td> 
      <td><input type="text" name="hinta" value ="<?= $tila['hinta'] ?>"> &#8364/h</td>
      <td><input type="text" name="muuta" value="<?= $tila['muuta'] ?>"></td>
   </tr>
</table>
<input type="submit" value="Tallenna muutokset">
</form>
<p>

<h3>Varaukset</h3>
<table><tr><td></td>
<?php //Kalenterin tulostus
for($i = 0; $i < 14; $i++)
   echo "<td>$date[$i]</td>";
echo "</tr>\n";

for($i = $tila['alkuaika']; $i < $tila['loppuaika']; $i++){
   echo "<tr><td>$i:00</td>";
   for($k = 0; $k < 14; $k++){
      if($varaus['alkuaika'] <= $i && $i < $varaus['loppuaika'] && $varaus['pvm'] == $date[$k])
         echo "<td>Varattu</td>";
   else
      echo "<td><form action='varaa'><input type='hidden' value='".$tila['tila']."' name='tila'>
       <input type='hidden' value='$i' name='aika'>
       <input type='hidden' value='$date[$k]' name='pvm'>
          <input type='submit' value='Varaa'></form></td>";
   }
    echo "</tr>\n";
}
?>
<table>
