<H1>Vaihda salasanasi</h1>

<form method="POST">
    <table class="lomake">
        <tr><td>Vanha salasana:</td><td> <input type="password" name="vanha"></td></tr>
        <tr><td>Uusi salasana:</td><td> <input type="password" name="uusi1"></td></tr>
        <tr><td>Toista uusi salasana:</td><td> <input type="password" name="uusi2"></td></tr>
    </table><br>
    <input type="submit" value="Vaihda salasana">
</form>
<p>
    <a href="<?php echo Atomik::url('index'); ?>">Takaisin</a>